//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MFCUI.rc 使用
//
#define IDC_EDIT3_BoxNumber             0
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MFCUI_DIALOG                102
#define ID_INDICATOR_COUNT              102
#define ID_T1                           102
#define IDS_T1                          102
#define ID_INDICATOR_TIME               103
#define IDS_T2                          103
#define ID_INDICATOR_IP                 104
#define ID_T3                           104
#define IDS_T3                          104
#define IDI_ICON1                       128
#define IDR_ACCELERATOR1                133
#define IDI_Excel                       143
#define IDI_Sql                         144
#define IDI_Image                       145
#define IDI_Txt                         147
#define IDI_ICON3                       151
#define IDI_Close                       152
#define IDB_Logo                        153
#define IDI_Code                        155
#define IDI_Grab                        159
#define IDD_SPLASH                      160
#define IDD_NG                          166
#define IDI_Delete                      168
#define IDD_NOCAMERA                    169
#define IDD_NOUNIQUEC                   171
#define IDD_NOOPENC                     173
#define IDD_WELCOME                     175
#define IDR_MENU1                       179
#define IDC_STATIC_Setting              1000
#define IDC_STATIC_Setting2             1001
#define IDC_EDIT1_Row                   1002
#define IDC_EDIT2_Column                1003
#define IDC_CHECK1                      1004
#define IDC_EDIT1_Total                 1004
#define IDC_CHECK2                      1005
#define IDC_EDIT1_Row3                  1005
#define IDC_EDIT1_Dealed                1005
#define IDC_BUTTON2_Start               1006
#define IDC_BUTTON3_Image               1007
#define IDC_BUTTON2_Start2              1008
#define IDC_BUTTON2_Deal                1009
#define IDC_BUTTON4_Sql                 1010
#define IDC_BUTTON5_Txt                 1011
#define IDC_BUTTON6_Excel               1012
#define IDC_BUTTON5_Txt2                1012
#define IDC_BUTTON5_Excel               1012
#define IDC_BUTTON_Grab                 1013
#define IDC_EDIT4_SampleType            1022
#define IDC_EDIT5_BoxDescription        1023
#define IDC_EDIT6_BoxLocation           1024
#define IDC_LIST                        1037
#define IDC_BUTTON_ChangeContext        1038
#define IDC_EDIT_ChangeContext          1039
#define IDC_STATIC_Image                1040
#define IDC_RADIO1                      1041
#define IDC_STATIC_Camera               1041
#define IDC_RADIO2                      1042
#define IDC_BUTTON_Exit                 1043
#define IDC_BUTTON1                     1044
#define IDC_BUTTON1_Fresh               1044
#define IDC_COMBO1                      1045
#define IDC_BUTTON2                     1045
#define IDC_STATIC1                     1053
#define IDC_STATIC2                     1054
#define IDC_STATIC3                     1055
#define IDC_STATIC4                     1056
#define IDC_STATIC5                     1057
#define IDC_STATIC6                     1058
#define IDC_STATIC7                     1059
#define IDC_STATIC8                     1060
#define IDC_STATIC9                     1061
#define IDC_STATIC10                    1062
#define IDC_STATIC11                    1063
#define IDC_STATIC14                    1064
#define IDC_STATIC12                    1065
#define IDC_STATIC13                    1066
#define IDC_STATIC15                    1067
#define IDC_STATICqi                    1068
#define IDC_STATIC_Trail1               1069
#define IDC_STATIC_Trail2               1070
#define IDC_MFCEDITBROWSE1              1071
#define IDC_STATIC0                     1072
#define IDC_STATIC_Total                1073
#define IDC_STATIC_Dealed               1074
#define IDC_BUTTON_Reg                  1077
#define IDC_STATICR                     1079
#define IDC_BUTTON_OutSql               1080
#define IDC_EDIT_OutSql                 1081
#define IDC_STATIC18                    1082
#define IDC_STATICOutsql                1083
#define IDC_STATIC_SN                   1088
#define IDC_STATIC_Introduction         1092
#define IDC_STATIC_Loading              1093
#define IDC_BUTTON_English              1095
#define IDC_STATIC_Language             1096
#define IDC_COMBO2                      1097
#define IDC_BUTTON_English2             1097
#define IDC_BUTTON_Chinese              1097
#define IDC_COMBO_Camera                1098
#define ID_LANGUAGE_CHINESE             32780
#define ID_Menu                         32781
#define ID_LANGUAGE_ENGLISH             32782
#define ID_Menu32783                    32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
